name: release-tag
on:
  push:
    tags:
      - "[0-9].*"
  pull_request:
    branches:
      - master

jobs:
  escript:
    runs-on: ubuntu-latest
    container: erlang:23
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      # - name: Build escript
      #   run: rebar3 escriptize
      - name: Fetch latest release information
        uses: octokit/request-action@v2.x
        id: latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: ${{ github.repository_owner }}
          repo: woorl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build changelog
        uses: ./.github/actions/generate-changelog
        id: changelog
        with:
          sinceTag: ${{ fromJSON(steps.latest_release.outputs.data).tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        uses: ncipollo/release-action@v1.8.9
        with:
          artifacts: "_build/default/bin/*"
          body: ${{ steps.changelog.outputs.changelog }}
          # token: ${{ secrets.GITHUB_TOKEN }}
